esphome:
  name: living-room-nabu

esp32:
  board: waveshare_esp32_s3_zero
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "no"

ota:
  - platform: esphome
    password: "no"

wifi:
  ssid: "Roshar"
  password: "retspecdps"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living-Room-Nabu"
    password: "Q9DcPeyrFkIP"

captive_portal:

i2c:
  sda: gpio_11
  scl: gpio_10
  scan: true
  id: bus_a
tca9555:
  - id: 'TCA9555_hub'
time:
  - platform: pcf85063
    id: pcf85063_time
    pin:
      tca9555: tca9555_hub
      # Use pin number 0
      number: 5
output:
  - platform: ledc
    pin: gpio_38
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

binary_sensor:
  - platform: gpio
    pin: CHIP_PU
    name: "Reset"
  - platform: gpio
    pin: gpio_0
    name: "Boot"
  - platform: gpio # Volume up?
    pin:
      tca9555: tca9555_hub
      # Use pin number 0
      number: 10
    name: "KEY1"
  - platform: gpio # Volume down?
    pin:
      tca9555: tca9555_hub
      # Use pin number 0
      number: 11
    name: "KEY2"
  - platform: gpio # Wake button?
    pin:
      tca9555: tca9555_hub
      # Use pin number 0
      number: 12
    name: "KEY3"

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO14
    i2s_bclk_pin: GPIO13
    i2s_mclk_pin: GPIO12

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external